/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as assetASol from "./AssetA.sol";
export type { assetASol };
import type * as assetBSol from "./AssetB.sol";
export type { assetBSol };
import type * as liquiditySol from "./Liquidity.sol";
export type { liquiditySol };
export type { AMM } from "./AMM";
export type { GOV } from "./GOV";
